name: 'Test Plugin with different AGP'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  localPluginTestDifferentAGP:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # We are aiming to test 5 different AGP versions
        # 1. The current stable one
        # 2. The latest three releases
        # 3. The next after the current stable (alpha or beta doesn't matter)
        # The test cases needs to be updated regularly here
        # https://maven.google.com/web/index.html?q=gradle#com.android.tools.build:gradle
        agp_version: [ '8.1.4', '8.2.2', '8.3.2', '8.4.0', '8.5.0-alpha08' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-caches-v0-${{ hashFiles('build.gradle.kts', 'settings.gradle.kts', 'gradle/wrapper/gradle-wrapper.properties', 'gradle/libs.versions.tml') }}

      - name: Change AGP version
        run: |
          export VERSION=${{ matrix.agp_version }} 
          sed -i "s/com\.android\.tools\.build:gradle:[0-9]\+\.[0-9]\+\.[0-9]\+/com.android.tools.build:gradle:$VERSION/" ./gradle/libs.versions.toml
          cat gradle/libs.versions.toml

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run 'normal' tests
        run: ./gradlew test --tests 'SentryProguardGradlePluginTest'
